[package]
name = "parcours"
description = "Parser Combinators for Unique Results"
authors = ["Michael Färber <michael.faerber@gedenkt.at>"]
version = "0.1.0"
edition = "2018"
license = "MIT"
repository = "https://github.com/01mf02/parcours"
categories = ["parsing"]
rust-version = "1.53"
