name: Build and run tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**/Cargo.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.63

    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
